services:
  - type: web
    name: koimp3-api
    runtime: docker
    plan: free

    healthCheckPath: /health

    envVars:
      - key: MAX_DURATION_SECONDS
        value: "1800"

      - key: JOB_TTL_SECONDS
        value: "1800"
